### ISSUE TITLE
Does the Tickit CPAN distribution have a repo?

### ISSUE THREAD

**Issue by cxw42** [ingydotnet/tickit-info#12]
@ingydotnet, @leonerd, I just recently discovered Tickit and it looks very interesting!  I am running on Cygwin, and it doesn't compile.  If/when I fix that, is there a repo I can submit the changes to?  I see this repo is on 0.64, but there's a [0.65 on CPAN](https://metacpan.org/pod/Tickit).  Other than this repo, I see:

- https://github.com/leonerd/python-tickit (not the CPAN distr) 
- http://home.leonerd.org.uk/code/libtickit/ and corresponding https://code.launchpad.net/~leonerd/libtickit (just the underlying library)
- http://bazaar.leonerd.org.uk/perl/Tickit/ (empty directory)

I'm sorry if I'm simply missing something obvious!  Please let me know (as I'm not sure where else to ask this question!).  Thank you!

**Comment by leonerd** [comment]
Ah, Cygwin. :) Good luck - would be exciting to see that working.

As to source control: http://bazaar.leonerd.org.uk/perl/Tickit/ is the Bazaar branch; it just looks empty because the webserver frontend doesn't list the `.bzr` directory inside it. You could use it by

    $ bzr branch http://bazaar.leonerd.org.uk/perl/Tickit/

Or alternatively just a patch against latest CPAN version should be fine.

**Comment by cxw42** [comment]
@leonerd Ah!  Dotfiles (and my own ignorance) strike again :) .  Much appreciated!

**Comment by cxw42** [comment]
@leonerd I emailed you (your @ leonerd org uk addr) a small merge directive to add a CONTRIBUTING file reflecting the above.  At your convenience, would you please check your email/spam box and let me know whether or not you received it?  Thanks!
